// src/components/Pagination.vue
<script setup lang="ts">
const { order } = defineProps<{
  order: number;
}>();

const pages = useDocuments("~/pages/start").value;
const next = pages.find((p) => p.frontmatter.order === order + 1);
const previous = pages.find((p) => p.frontmatter.order === order - 1);
</script>

<template>
  <div
    class="text-normal flex flex-col items-center justify-between tracking-tight md:flex-row md:text-lg lg:text-xl"
  >
    <div>
      <span v-if="previous" class="flex space-x-4">
        <span>&larr;</span>
        <a :href="previous.href" class="font-semibold hover:text-primary">
          {{ previous.frontmatter.title }}
        </a>
      </span>
    </div>

    <div>
      <span v-if="next" class="flex space-x-4">
        <a :href="next.href" class="font-semibold hover:text-primary">
          {{ next.frontmatter.title }}
        </a>
        <span>&rarr;</span>
      </span>
    </div>
  </div>
</template>

// components/start/Pagination.tsx
import { allSteps, Step } from "contentlayer/generated";
import Link from "next/link";

type Props = {
  weight: number;
};

const Pagination = ({ weight }: Props) => {
  const next: Step | undefined = allSteps.find((s) => s.weight === weight + 1);
  const previous: Step | undefined = allSteps.find(
    (s) => s.weight === weight - 1
  );

  return (
    <>
      {(previous || next) && (
        <div className="mt-12 px-6 py-4">
          <div className="container mx-auto">
            <div className="md:flex justify-between items-center">
              <div>
                {previous && (
                  <>
                    <span className="mr-2">Previous:</span>
                    <Link
                      href={previous.path}
                      className="font-semibold hover:text-blue-500"
                    >
                      {previous.title}
                    </Link>
                  </>
                )}
              </div>

              <div>
                {next && (
                  <>
                    <span className="mr-2">Next:</span>
                    <Link
                      href={next.path}
                      className="font-semibold hover:text-blue-500"
                    >
                      {next.title}
                    </Link>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default Pagination;
