// components/Footer.tsx
import Link from "next/link";

const Footer = () => {
  const year = new Date().getFullYear();

  return (
    <footer className="bg-slate-100 pt-8 pb-16 px-6">
      <div className="container mx-auto">
        <p>
          Copyright &copy; {year}{" "}
          <Link
            href="https://determinate.systems"
            className="hover:text-blue-500"
          >
            Determinate Systems
          </Link>
        </p>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/layout/Footer.vue
<template>
  <footer class="dark:bg-dark">
    <HorizontalContainer>
      <div class="flex justify-end pb-16 pt-12">
        <p
          class="tracking-tight text-gray dark:text-gray md:text-base lg:text-lg"
        >
          Copyright &copy; {{ year }}
          <a href="https://determinate.systems" class="hover:text-primary">
            Determinate Systems, Inc.
          </a>
        </p>
      </div>
    </HorizontalContainer>
  </footer>
</template>

<script setup lang="ts">
const year = new Date().getFullYear();
</script>
