// components/Navbar.tsx
"use client";

import clsx from "clsx";
import { state } from "lib/state";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import site from "site";
import shallow from "zustand/shallow";

type NavLink = {
  text: string;
  href: string;
};

const links: NavLink[] = [
  { text: "Quick start", href: "/start" },
  { text: "Concepts", href: "/concepts" },
];

const Navbar = () => {
  const [system, setSystem] = state((s) => [s.system, s.setSystem], shallow);
  const [sys, setSys] = useState<string>();

  useEffect(() => {
    setSys(system);
  }, [system]);

  const { title } = site;

  const here = usePathname()!;

  return (
    <nav className="sticky top-0 bg-slate-100 py-4 px-6 shadow">
      <div className="container mx-auto flex justify-between items-center">
        <div>
          <Link href="/" className="text-xl font-semibold hover:text-blue-500">
            {title}
          </Link>
        </div>

        <div className="flex items-center space-x-6">
          {links.map((link) => (
            <Link
              key={link.text}
              href={link.href}
              className={clsx(
                here.startsWith(link.href) ? "font-bold" : "font-normal"
              )}
            >
              {link.text}
            </Link>
          ))}
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// src/components/layout/Navbar.vue
<template>
  <nav
    class="sticky top-0 border-b-2 border-light-gray bg-white/75 py-2 backdrop-blur dark:border-b-gray dark:bg-dark md:py-2.5 lg:py-3"
  >
    <HorizontalContainer>
      <div class="flex items-center justify-between">
        <div class="flex items-center space-x-2 md:space-x-3 lg:space-x-4">
          <a
            href="/"
            class="text-2xl font-semibold tracking-tighter hover:text-primary dark:hover:text-primary md:text-3xl lg:text-4xl"
          >
            {{ $site.title }}
          </a>

          <IconAppNix
            class="h-5 w-5 fill-sky-600 dark:fill-sky-400 md:h-6 md:w-6 lg:h-7 lg:w-7"
          />
        </div>

        <ul class="flex items-center space-x-4 md:space-x-5 lg:space-x-6">
          <li>
            <Dropdown
              :dropdown="{ text: 'Quick start', pages: sortedQuickStartPages }"
              client:load
            />
          </li>
          <li>
            <Dropdown
              :dropdown="{ text: 'Concepts', pages: conceptPages }"
              client:load
            />
          </li>
          <li class="flex items-center space-x-2 md:space-x-3 lg:space-x-4">
            <ThemeSwitcher client:load />

            <a :href="$site.githubUrl">
              <IconFaGithub
                class="h-4 w-4 hover:text-gray dark:hover:text-light-gray md:h-5 md:w-5 lg:h-6 lg:w-6"
              />
            </a>
          </li>
        </ul>
      </div>
    </HorizontalContainer>
  </nav>
</template>

<script setup lang="ts">
import { conceptPages, sortedQuickStartPages } from "~/logic/content";
</script>
