// src/components/Navbar.vue
<script setup lang="ts">
const {
  route: { path },
} = usePage();
</script>

<template>
  <nav
    class="bg-white border-light-gray border-b-2 py-2 top-0 sticky md:py-2.5 lg:py-3 dark:bg-black dark:border-b-gray"
  >
    <HorizontalContainer>
      <div class="flex justify-between items-center">
        <div class="flex space-x-2 items-center md:space-x-3 lg:space-x-4">
          <a
            href="/"
            class="font-semibold tracking-tighter text-2xl md:text-3xl lg:text-4xl hover:text-primary dark:hover:text-primary"
            >{{ $site.title }}</a
          >

          <NixLogo />
        </div>

        <ul class="flex space-x-4 items-center md:space-x-5 lg:space-x-6">
          <li v-for="link in $site.navbarLinks" :key="link.text">
            <a
              :href="link.href"
              class="text-normal md:text-lg lg:text-xl hover:text-blue dark:hover:text-light-blue"
              :class="{
                'font-semibold': path.startsWith(link.href),
                'font-normal': !path.startsWith(link.href),
              }"
              >{{ link.text }}</a
            >
          </li>
          <li class="flex items-center">
            <ThemeSwitcher client:load />
          </li>
        </ul>
      </div>
    </HorizontalContainer>
  </nav>
</template>

// components/Navbar.tsx
"use client";

import clsx from "clsx";
import { state } from "lib/state";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import site from "site";
import shallow from "zustand/shallow";

type NavLink = {
  text: string;
  href: string;
};

const links: NavLink[] = [
  { text: "Quick start", href: "/start" },
  { text: "Concepts", href: "/concepts" },
];

const Navbar = () => {
  const [system, setSystem] = state((s) => [s.system, s.setSystem], shallow);
  const [sys, setSys] = useState<string>();

  useEffect(() => {
    setSys(system);
  }, [system]);

  const { title } = site;

  const here = usePathname()!;

  return (
    <nav className="sticky top-0 bg-slate-100 py-4 px-6 shadow">
      <div className="container mx-auto flex justify-between items-center">
        <div>
          <Link href="/" className="text-xl font-semibold hover:text-blue-500">
            {title}
          </Link>
        </div>

        <div className="flex items-center space-x-6">
          {links.map((link) => (
            <Link
              key={link.text}
              href={link.href}
              className={clsx(
                here.startsWith(link.href) ? "font-bold" : "font-normal"
              )}
            >
              {link.text}
            </Link>
          ))}
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
