// components/Footer.tsx
import Link from "next/link";

const Footer = () => {
  const year = new Date().getFullYear();

  return (
    <footer className="bg-slate-100 pt-8 pb-16 px-6">
      <div className="container mx-auto">
        <p>
          Copyright &copy; {year}{" "}
          <Link
            href="https://determinate.systems"
            className="hover:text-blue-500"
          >
            Determinate Systems
          </Link>
        </p>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/Footer.vue
<template>
  <footer class="dark:bg-black">
    <HorizontalContainer>
      <div class="pt-12 pb-16">
        <p
          class="md:text-normal text-right text-sm font-light tracking-tight lg:text-lg"
        >
          Copyright &copy; {{ $site.year }}
          <a href="https://determinate.systems" class="hover:text-primary">
            Determinate Systems
          </a>
        </p>
      </div>
    </HorizontalContainer>
  </footer>
</template>
