// src/components/Harmonic.tsx
import { useStore } from "@nanostores/react";

import { system } from "../data/store";

type Command = "plan" | "install";

type Props = {
  command: Command;
};

const Harmonic = ({ command }: Props) => {
  const $system = useStore(system);

  const arch = $system == "Linux" ? "linux" : "darwin";

  let script: string;

  switch (command) {
    case "plan":
      script = `harmonic plan install ${arch}-multi`;
      break;
    case "install":
      script = `harmonic install ${arch}-multi`;
      break;
  }

  return (
    <pre>
      <code className="language-shell">{script}</code>
    </pre>
  );
};

export default Harmonic;

// src/components/Harmonic.vue
<script setup lang="ts">
import { system } from "~/logic/state";

const props = defineProps<{
  command: string;
}>();

const { command } = props;
</script>

<template>
  <div class="language-shell" data-lang="shell">
    <pre
      class="language-shell"
    ><code>harmonic {{ command }} {{ `${system === "Linux" ? "linux" : "darwin"}-multi` }}</code></pre>
  </div>
</template>
