// src/components/Languages.vue
<script setup lang="ts">
import { language, languageState } from "~/logic/state";
import site from "~/site";

const { languages } = site;
</script>

<template>
  <div
    className="not-prose text-normal inline-flex items-center space-x-6 rounded-lg border-2 border-light-gray bg-pale p-3 dark:border-gray dark:bg-black"
  >
    <p
      className="text-normal font-semibold tracking-tight md:text-lg lg:text-xl"
    >
      Select your language
    </p>

    <button
      v-for="lang in languages"
      :key="lang"
      @click="languageState.set(lang)"
      class="mg:text-normal rounded-lg py-0 px-2 text-sm font-semibold md:py-0.5 md:px-3 lg:py-1 lg:px-4 lg:text-lg"
      :class="{ 'bg-primary text-white': lang === language }"
    >
      {{ lang }}
    </button>
  </div>
</template>

// src/components/Languages.tsx
import { useStore } from "@nanostores/react";
import clsx from "clsx";

import { language, languages } from "../data/store";

const Languages = () => {
  const $language = useStore(language);

  return (
    <div>
      <div className="flex space-x-2">
        {languages.map((l) => (
          <button
            key={l}
            onClick={() => language.set(l)}
            className={clsx(
              "py-1 px-3 rounded-lg shadow font-semibold",
              l === $language
                ? "bg-black text-white"
                : "bg-slate-200 text-black hover:bg-slate-300"
            )}
          >
            {l}
          </button>
        ))}
      </div>
    </div>
  );
};

export default Languages;
