// components/mdx/Languages.tsx
import clsx from "clsx";
import { languages, state } from "lib/state";
import { useEffect, useState } from "react";

const Languages = () => {
  const [language, setLanguage] = state((s) => [s.language, s.setLanguage]);
  const [lang, setLang] = useState<string>();

  useEffect(() => {
    setLang(language);
  }, [language]);

  return (
    <>
      <div className="not-prose">
        <div className="space-x-2">
          {languages.map((l) => (
            <button
              key={l}
              className={clsx(
                "py-1 px-3 rounded-lg font-semibold shadow tracking-tight",
                l === lang
                  ? "bg-slate-800 text-white"
                  : "bg-slate-100 text-black hover:bg-slate-200"
              )}
              onClick={() => setLanguage(l)}
            >
              {l}
            </button>
          ))}
        </div>
      </div>
    </>
  );
};

export default Languages;

// src/components/Languages.vue
<script setup lang="ts">
import { language, languageState } from "~/logic/state";
import site from "~/site";

const { languages } = site;
</script>

<template>
  <div
    className="not-prose text-normal inline-flex items-center space-x-6 rounded-lg border-2 border-light-gray bg-pale p-3 dark:border-gray dark:bg-black"
  >
    <p
      className="text-normal font-semibold tracking-tight md:text-lg lg:text-xl"
    >
      Select your language
    </p>

    <button
      v-for="lang in languages"
      :key="lang"
      @click="languageState.set(lang)"
      class="mg:text-normal rounded-lg py-0 px-2 text-sm font-semibold md:py-0.5 md:px-3 lg:py-1 lg:px-4 lg:text-lg"
      :class="{ 'bg-primary text-white': lang === language }"
    >
      {{ lang }}
    </button>
  </div>
</template>
