// components/docs/Pagination.tsx
import { Doc } from "contentlayer/generated";
import Link from "next/link";

type Props = {
  previous?: Doc;
  next?: Doc;
};

const Pagination = ({ previous, next }: Props) => {
  return (
    <>
      {(previous || next) && (
        <div className="inline-flex justify-between items-center">
          <div>
            {previous && (
              <>
                <span className="mr-2">Previous:</span>
                <Link
                  href={previous.path}
                  className="font-semibold hover:text-blue-500"
                >
                  {previous.title}
                </Link>
              </>
            )}
          </div>

          <div>
            {next && (
              <>
                <span className="mr-2">Next:</span>
                <Link
                  href={next.path}
                  className="font-semibold hover:text-blue-500"
                >
                  {next.title}
                </Link>
              </>
            )}
          </div>
        </div>
      )}
    </>
  );
};

export default Pagination;

// src/components/Pagination.vue
<script setup lang="ts">
import { getPrevious, getNext, QuickStartPage } from "../content";

const { order } = defineProps<{
  order: number;
}>();

const previous: QuickStartPage | undefined = getPrevious(order);
const next: QuickStartPage | undefined = getNext(order);
</script>

<template>
  <div
    class="text-normal flex flex-col items-center justify-between tracking-tight md:flex-row md:text-lg lg:text-xl"
  >
    <div>
      <span v-if="previous" class="flex space-x-4">
        <span>&larr;</span>
        <a :href="previous.href" class="font-semibold hover:text-primary">
          {{ previous.frontmatter.title }}
        </a>
      </span>
    </div>

    <div>
      <span v-if="next" class="flex space-x-4">
        <a :href="next.href" class="font-semibold hover:text-primary">
          {{ next.frontmatter.title }}
        </a>
        <span>&rarr;</span>
      </span>
    </div>
  </div>
</template>
