// src/components/Systems.vue
<script setup lang="ts">
import site from "~/site";
const { systems } = site;

import { Tab } from "@headlessui/vue";

import { useStore } from "@nanostores/vue";
import { systemState } from "~/logic/state";

const system = useStore(systemState);
</script>

<template>
  <div
    className="not-prose text-normal inline-flex items-center space-x-6 rounded-lg border-2 border-light-gray bg-pale p-3 dark:border-gray dark:bg-black"
  >
    <p
      className="text-normal font-semibold tracking-tight md:text-lg lg:text-xl"
    >
      Select your platform
    </p>

    <button
      v-for="sys in systems"
      :key="sys"
      @click="systemState.set(sys)"
      class="mg:text-normal rounded-lg py-0 px-2 text-sm font-semibold md:py-0.5 md:px-3 lg:py-1 lg:px-4 lg:text-lg"
      :class="{ 'bg-primary text-white': sys === system }"
    >
      {{ sys }}
    </button>
  </div>
</template>

// src/components/Systems.tsx
import { Tab } from "@headlessui/react";
import { useStore } from "@nanostores/react";
import clsx from "clsx";
import { Fragment } from "react";

import { system, systems } from "../data/store";

const Systems = () => {
  const $system = useStore(system);

  return (
    <>
      <Tab.Group>
        <Tab.List as="div" className="space-x-2">
          {systems.map((s) => (
            <Tab as={Fragment}>
              <button
                key={s}
                onClick={() => system.set(s)}
                className={clsx(
                  "py-1 px-3 rounded-lg shadow font-semibold",
                  $system === s
                    ? "bg-black text-white"
                    : "bg-slate-200 text-black hover:bg-slate-300"
                )}
              >
                {s}
              </button>
            </Tab>
          ))}
        </Tab.List>
      </Tab.Group>
    </>
  );
};

export default Systems;
