// src/components/generic/Selector.tsx
import { Tab } from "@headlessui/react";
import { useStore } from "@nanostores/react";
import clsx from "clsx";
import type { StoreValue, WritableAtom } from "nanostores";
import { Fragment } from "react";

type Props = {
  title: string;
  options: string[];
  atom: WritableAtom<string>;
};

const Selector = ({ title, options, atom }: Props) => {
  const $item: string = useStore<StoreValue<string>>(atom);

  return (
    <div className="not-prose inline-flex items-center space-x-6 border-2 bg-pale border-light-gray rounded-xl py-4 px-6 shadow-sm dark:bg-black dark:border-gray">
      <p className="text-xl font-semibold tracking-tight">{title}</p>
      <Tab.Group onChange={(idx: number) => atom.set(options[idx]!)}>
        <Tab.List as="div" className="flex space-x-3">
          {options.map((o) => (
            <Tab as={Fragment}>
              <button
                aria-label={title}
                key={o}
                onClick={() => atom.set(o)}
                className={clsx(
                  "px-3 rounded-lg font-semibold text-normal",
                  $item === o && "bg-primary text-white"
                )}
              >
                {o}
              </button>
            </Tab>
          ))}
        </Tab.List>
      </Tab.Group>
    </div>
  );
};

export default Selector;

// src/components/mdx/stateful/Selector.vue
<template>
  <div
    className="not-prose text-normal inline-flex items-center space-x-6 rounded-lg border-2 border-light-gray bg-pale p-3 dark:border-gray dark:bg-inherit"
  >
    <p
      className="text-normal font-semibold tracking-tight md:text-lg lg:text-xl"
    >
      {{ title }}
    </p>

    <TabGroup @change="update" :defaultIndex="defaultIndex">
      <TabList>
        <Tab
          v-for="(option, idx) in options"
          :key="idx"
          as="template"
          v-slot="{ selected }"
        >
          <button
            class="mg:text-normal rounded-lg py-0 px-2 text-sm font-semibold md:py-0.5 md:px-3 lg:py-1 lg:px-4 lg:text-lg"
            :class="{ 'bg-primary text-white': selected }"
          >
            {{ option }}
          </button>
        </Tab>
      </TabList>
    </TabGroup>
  </div>
</template>

<script setup lang="ts">
import { Tab, TabGroup, TabList } from "@headlessui/vue";
import { useStore } from "@nanostores/vue";
import { WritableAtom } from "nanostores";

const { title, options, state } = defineProps<{
  title: string;
  options: string[];
  state: WritableAtom<string>;
}>();

const store = useStore(state);

const defaultIndex = options.indexOf(store.value);

const update = (idx: number) => {
  state.set(options[idx]);
};
</script>
