// components/mdx/Systems.tsx
import { Tab } from "@headlessui/react";
import clsx from "clsx";
import { state, systems } from "lib/state";
import { Fragment, useEffect, useState } from "react";

const Systems = () => {
  const [system, setSystem] = state((s) => [s.system, s.setSystem]);
  const [_, setSys] = useState<string>();

  useEffect(() => {
    setSys(system);
  }, [system]);

  return (
    <Tab.Group>
      <Tab.List as="div" className="flex space-x-2">
        {systems.map((s) => (
          <Tab key={s} as={Fragment}>
            {({ selected }) => (
              <button
                onClick={() => setSystem(s)}
                className={clsx(
                  "py-1 px-3 rounded-lg font-semibold shadow tracking-tight",
                  selected
                    ? "bg-slate-800 text-white"
                    : "bg-slate-100 text-black hover:bg-slate-200"
                )}
              >
                {s}
              </button>
            )}
          </Tab>
        ))}
      </Tab.List>
    </Tab.Group>
  );
};

export default Systems;

// src/components/mdx/stateful/Systems.vue
<template>
  <div
    className="not-prose text-normal inline-flex items-center space-x-6 rounded-lg border-2 border-light-gray bg-pale p-3 dark:border-gray dark:bg-inherit"
  >
    <p
      className="text-normal font-semibold tracking-tight md:text-lg lg:text-xl"
    >
      Select your platform
    </p>

    <TabGroup @change="updateSystem" :defaultIndex="defaultIndex">
      <TabList>
        <Tab
          v-for="(sys, idx) in systems"
          :key="idx"
          as="template"
          v-slot="{ selected }"
        >
          <button
            class="mg:text-normal rounded-lg py-0 px-2 text-sm font-semibold md:py-0.5 md:px-3 lg:py-1 lg:px-4 lg:text-lg"
            :class="{ 'bg-primary text-white': selected }"
          >
            {{ sys }}
          </button>
        </Tab>
      </TabList>
    </TabGroup>
  </div>
</template>

<script setup lang="ts">
import { Tab, TabGroup, TabList } from "@headlessui/vue";
import { system, systemState } from "~/logic/state";
import site from "~/site";

const { systems } = site;

const defaultIndex = systems.indexOf(system.value);

const updateSystem = (idx: number) => {
  systemState.set(systems[idx]);
};
</script>
