// src/components/mdx/concepts/NixStorePath.vue
<script setup lang="ts">
const { pkg } = defineProps<{
  pkg: string;
}>();
</script>

<template>
  <div
    class="not-prose rounded-lg border-2 border-light-gray bg-pale py-3 px-5 dark:border-gray dark:bg-inherit"
  >
    <div class="space-y-2 md:space-y-3 lg:space-y-4">
      <pre
        class="flex overflow-auto whitespace-normal break-keep text-lg md:text-xl lg:text-2xl xl:text-3xl"
      >
        <div class="flex flex-col md:space-y-1 lg:space-y-1.5">
          <span class="font-mono text-lilac dark:text-cerulean">
            /nix/store/
          </span>
          <span class="md:text-normal font-sans text-sm tracking-tight lg:text-lg">
            <strong>1.</strong> Root path
          </span>
        </div>
        <div class="flex flex-col md:space-y-1.5 lg:space-y-1.5">
          <span class="font-mono font-light text-blue dark:text-lilac">
            sglc12hc6pc68w5ppn2k56n6jcpaci16
          </span>
          <span class="md:text-normal font-sans text-sm tracking-tight lg:text-lg">
            <strong>2.</strong> Input hash
          </span>
        </div>
        <span>-</span>
        <div class="flex flex-col md:space-y-1.5 lg:space-y-1.5">
          <span class="font-mono text-orange dark:text-rose">{{ pkg }}</span>
          <span class="md:text-normal font-sans text-sm tracking-tight lg:text-lg">
            <strong>3.</strong> Package name
          </span>
        </div>
      </pre>
    </div>
  </div>
</template>

// src/components/concepts/NixStorePath.tsx
type Props = {
  pkg: string;
};

const NixStorePath = ({ pkg }: Props) => {
  return (
    <div className="not-prose rounded-lg bg-pale dark:bg-black border-2 border-light-gray dark:border-gray py-3 px-5">
      <div className="space-y-2 md:space-y-3 lg:space-y-4">
        <pre className="overflow-auto text-lg md:text-xl lg:text-2xl xl:text-3xl flex">
          <div className="flex flex-col md:space-y-1 lg:space-y-1.5">
            <span className="text-lilac dark:text-cerulean font-mono">
              /nix/store/
            </span>
            <span className="font-sans tracking-tight text-sm md:text-normal lg:text-lg">
              <strong>1.</strong> Root path
            </span>
          </div>
          <div className="flex flex-col md:space-y-1.5 lg:space-y-1.5">
            <span className="text-blue dark:text-lilac font-light font-mono">
              sglc12hc6pc68w5ppn2k56n6jcpaci16
            </span>
            <span className="font-sans tracking-tight text-sm md:text-normal lg:text-lg">
              <strong>2.</strong> Input hash
            </span>
          </div>
          <span>-</span>
          <div className="flex flex-col md:space-y-1.5 lg:space-y-1.5">
            <span className="text-orange dark:text-rose font-mono">{pkg}</span>
            <span className="font-sans tracking-tight text-sm md:text-normal lg:text-lg">
              <strong>3.</strong> Package name
            </span>
          </div>
        </pre>
      </div>
    </div>
  );
};

export default NixStorePath;
